"""empty message

Revision ID: 9023d425335d
Revises: dcb0335ec2f6
Create Date: 2019-07-11 10:59:22.430378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9023d425335d'
down_revision = 'dcb0335ec2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favs_user_id', table_name='favs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_favs_user_id', 'favs', ['user_id'], unique=False)
    # ### end Alembic commands ###
