"""adding fav table and dog table

Revision ID: dcb0335ec2f6
Revises: d27682808512
Create Date: 2019-07-11 10:22:20.598772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0335ec2f6'
down_revision = 'd27682808512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('dog_name', sa.String(), nullable=True),
    sa.Column('dog_gender', sa.String(), nullable=True),
    sa.Column('dog_age', sa.String(), nullable=True),
    sa.Column('dog_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dog_id')
    )
    op.create_table('favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favs_dog_id'), 'favs', ['dog_id'], unique=False)
    op.create_index(op.f('ix_favs_user_id'), 'favs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favs_user_id'), table_name='favs')
    op.drop_index(op.f('ix_favs_dog_id'), table_name='favs')
    op.drop_table('favs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
