"""empty message

Revision ID: fa8a3652e0b4
Revises: 
Create Date: 2019-07-11 23:46:30.306823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8a3652e0b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('dog_name', sa.String(), nullable=True),
    sa.Column('dog_gender', sa.String(), nullable=True),
    sa.Column('dog_age', sa.String(), nullable=True),
    sa.Column('dog_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dog_id', name='fav_pair')
    )
    op.create_index(op.f('ix_favs_dog_id'), 'favs', ['dog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favs_dog_id'), table_name='favs')
    op.drop_table('favs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dogs')
    # ### end Alembic commands ###
